### PR TITLE
added abstract method decorator to authorization database

### PR DESCRIPTION
**Pull request by rajivsunar07**

### CODE REVIEW

**Comment by k0rsakov** [comment]
@rajivsunar07 Hi. Thanks for the merge request.

Did you run the tests? Did it affect the work of the classes?

**Comment by rajivsunar07** [comment]
Yes. I ran the tests in my local Postgresql db and all the tests passed.

**Comment by k0rsakov** [comment]
@rajivsunar07 Everything is fine. Thank you very much for your contribution.

**Comment by rajivsunar07** [comment]
You're welcome.

**Pull request merged**
